name: build-and-push-camera
on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/camera.Dockerfile
          push: true
          platforms: linux/arm64
         tags: ghcr.io/yachakawasi/raspi-camera:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
